---
##################
# Basic Settings #
##################

testing: 1 # 1 for True
take_new_photos_in_testing: 1 # 1 for True (i.e., take photos), 0 for False

# Working Start/ Finish - timelapse will take the more restrictive of this and sunrise/ sunset
workingStart: "6:00"
workingFinish: "17:00"

# Livestream duration in seconds
livestream_duration: 300
livestream_test_duration: 80

# The interval between captures (in seconds).
interval: 30

# Whether to create an video after capturing the time-lapse images.
create_video: True

# Whether to create an video after capturing the time-lapse images.
create_meta_video: True

# Image resolution Set to empty object (`{ }`) to use default resolution.
resolution:
  width: 1920
  height: 1080

#####################
# Advanced settings #
#####################

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 0

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 0

# White balance. Set to empty object (`{ }`) to use auto white balance.
white_balance:
  {}
  # red_gain: 1.3
  # blue_gain: 1.75

# Rotate the images taken by the camera. Possible value are 0, 90, 180 or 270
rotation: 0
