# Rename this file to config.py and fill out the fields

# Google Maps Auth
API_KEY = "AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXE"
D_ACCESS_TOKEN = "xnXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXcx"

# GMail settings
FROM_EMAIL = "SendersEmail@gmail.com"
TO_EMAIL = ["Recipient1@EmailProviderA.com, Recipient2@EmailProviderB.com"]
USER = "SendersEmail@gmail.com"
PASS = "tXXXXXXXXXXXXXXg"

# Twitch
STREAM_TOKEN = "lXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXy"

# AWS SQS
SQS_URL = "https://sqs.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXl"
SWS_ARN = "aXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXl"
AWS_ACCESS_KEY_ID = "AXXXXXXXXXXXXXXXXXXQ"
AWS_SECRET_ACCESS_KEY = "hXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXh"

# Project Location (Latitude and Longitude - NYC is default)
GPS_LOCATION = [40.730610, -73.935242]
